[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "fe621"
version = "0.1.0"
dependencies = [
    "numpy==2.4.2",
    "scipy==1.17.0",
]

[tool.setuptools.packages.find]
where = ["."]
namespaces = false